import os
'''This is an autogenerated script that will delete all references to RL-Glue from your machine if it is installed to the obvious place.'''
RLGlue_Files = RLGLUE_FILE_REPLACE_HERE

RLGlue_Files.append("/usr/local/bin/rl_glue")

for file in RLGlue_Files:
	try:
		print "Removing: "+file
		os.remove(file)
	except OSError:
		print("Unable to remove file: " + file)

RLGlue_Dirs=['/usr/local/include/rlglue/utils/C','/usr/local/include/rlglue/utils','/usr/local/include/rlglue/network','/usr/local/include/rlglue/']
for dir in RLGlue_Dirs:
	try:
		os.rmdir(dir)
	except OSError:
		print(dir)
